//! Shielded transfer (04) e2e in LiteSVM — the full flow:
//!   deposit (Alice shields 150) -> private transfer (Alice pays Bob 100, 50 change)
//!   -> withdraw (Bob unshields 100).
//!
//! Pre-creates an SPL mint + token accounts via `set_account` (no spl-token
//! instruction crate), then drives three real `transact` proofs generated by
//! circuits/transact/chain/. Each proof carries its own anchor root, nullifiers,
//! output commitments and new root; the program verifies, moves SPL for the
//! public value slots, burns nullifiers, and advances the tree.
mod common;
use common::{borsh_bytes, chunk32, disc, read, send, u64_at};

use std::str::FromStr;

use litesvm::types::TransactionResult;
use litesvm::LiteSVM;
use solana_account::Account;
use solana_address::Address;
use solana_instruction::{AccountMeta, Instruction};
use solana_keypair::Keypair;
use solana_signer::Signer;

const PROGRAM_ID: &str = "CUCcJJBRbK6tK4nPP2zgmvdYbKWSCGGVdRegtJ2GPJtF";
const TOKEN_PROGRAM: &str = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const RENT_SYSVAR: &str = "SysvarRent111111111111111111111111111111111";
const SYSTEM: &str = "11111111111111111111111111111111";
// Shared with the witness generator (`transfer-witness`) so the circuit's
// `asset` tag and the on-chain mint always agree.
use xark_examples_e2e::fixtures::{BOB_TOKEN_PUBKEY, MINT_PUBKEY, RECIPIENT};
const CHAIN: &str = "04-shielded-transfer/circuits/transact/chain";

fn tok(lamports: u64, data: Vec<u8>) -> Account {
    Account {
        lamports,
        data,
        owner: Address::from_str(TOKEN_PROGRAM).unwrap(),
        executable: false,
        rent_epoch: 0,
    }
}
fn mint_data(auth: &[u8; 32]) -> Vec<u8> {
    let mut d = vec![1, 0, 0, 0];
    d.extend_from_slice(auth);
    d.extend_from_slice(&0u64.to_le_bytes());
    d.push(0);
    d.push(1);
    d.extend_from_slice(&[0u8; 36]);
    d
}
fn token_data(mint: &[u8; 32], owner: &[u8; 32], amount: u64) -> Vec<u8> {
    let mut d = Vec::with_capacity(165);
    d.extend_from_slice(mint);
    d.extend_from_slice(owner);
    d.extend_from_slice(&amount.to_le_bytes());
    d.extend_from_slice(&[0u8; 36]);
    d.push(1);
    d.extend_from_slice(&[0u8; 12]);
    d.extend_from_slice(&0u64.to_le_bytes());
    d.extend_from_slice(&[0u8; 36]);
    d
}
fn token_amount(a: &Account) -> u64 {
    u64::from_le_bytes(a.data[64..72].try_into().unwrap())
}

#[allow(clippy::too_many_arguments)]
#[allow(clippy::result_large_err)]
fn transact(
    svm: &mut LiteSVM,
    program_id: Address,
    mint: Address,
    pool: Address,
    vault: Address,
    user: &Keypair,
    user_token: Address,
    recipient_token: Address,
    name: &str,
) -> TransactionResult {
    let proof = read(&format!("{CHAIN}/{name}_proof.bin"));
    let pi = read(&format!("{CHAIN}/{name}_pi.bin"));
    let root = chunk32(&pi, 0);
    let nf0 = chunk32(&pi, 2);
    let nf1 = chunk32(&pi, 3);
    let cm0 = chunk32(&pi, 4);
    let cm1 = chunk32(&pi, 5);
    let new_root = chunk32(&pi, 7);
    let (vpub_in, vpub_out, fee) = (u64_at(&pi, 9), u64_at(&pi, 10), u64_at(&pi, 11));

    let (nullifier0, _) =
        Address::find_program_address(&[b"nullifier", mint.as_ref(), &nf0], &program_id);
    let (nullifier1, _) =
        Address::find_program_address(&[b"nullifier", mint.as_ref(), &nf1], &program_id);

    let token_program = Address::from_str(TOKEN_PROGRAM).unwrap();
    let system = Address::from_str(SYSTEM).unwrap();

    let mut data = disc("transact").to_vec();
    data.extend_from_slice(&borsh_bytes(&proof));
    data.extend_from_slice(&root);
    data.extend_from_slice(&nf0);
    data.extend_from_slice(&nf1);
    data.extend_from_slice(&cm0);
    data.extend_from_slice(&cm1);
    data.extend_from_slice(&new_root);
    data.extend_from_slice(&vpub_in.to_le_bytes());
    data.extend_from_slice(&vpub_out.to_le_bytes());
    data.extend_from_slice(&fee.to_le_bytes());
    data.extend_from_slice(&borsh_bytes(format!("{name}-memo0").as_bytes()));
    data.extend_from_slice(&borsh_bytes(format!("{name}-memo1").as_bytes()));

    let ix = Instruction {
        program_id,
        accounts: vec![
            AccountMeta::new(pool, false),
            AccountMeta::new(vault, false),
            AccountMeta::new(nullifier0, false),
            AccountMeta::new(nullifier1, false),
            AccountMeta::new(user.pubkey(), true),
            AccountMeta::new(user_token, false),
            AccountMeta::new(recipient_token, false),
            AccountMeta::new_readonly(token_program, false),
            AccountMeta::new_readonly(system, false),
        ],
        data,
    };
    send(svm, ix, user)
}

#[test]
fn shielded_transfer_flow() {
    let program_id = Address::from_str(PROGRAM_ID).unwrap();
    let token_program = Address::from_str(TOKEN_PROGRAM).unwrap();
    let system = Address::from_str(SYSTEM).unwrap();
    let rent = Address::from_str(RENT_SYSVAR).unwrap();
    let mint = Address::new_from_array(MINT_PUBKEY);

    let mut svm = LiteSVM::new().with_mainnet_features();
    svm.add_program(
        program_id,
        &read("04-shielded-transfer/program/target/deploy/shielded_transfer.so"),
    )
    .unwrap();

    let alice = Keypair::new();
    svm.airdrop(&alice.pubkey(), 5_000_000_000).unwrap();
    svm.set_account(mint, tok(10_000_000, mint_data(&alice.pubkey().to_bytes())))
        .unwrap();
    let alice_token = Keypair::new().pubkey();
    svm.set_account(
        alice_token,
        tok(
            10_000_000,
            token_data(&MINT_PUBKEY, &alice.pubkey().to_bytes(), 150),
        ),
    )
    .unwrap();
    let bob_token = Address::new_from_array(BOB_TOKEN_PUBKEY);
    let bob_owner: [u8; 32] = RECIPIENT[32..].try_into().unwrap();
    svm.set_account(
        bob_token,
        tok(10_000_000, token_data(&MINT_PUBKEY, &bob_owner, 0)),
    )
    .unwrap();

    let (pool, _) = Address::find_program_address(&[b"pool", mint.as_ref()], &program_id);
    let (vault, _) = Address::find_program_address(&[b"vault", mint.as_ref()], &program_id);

    // initialize
    send(
        &mut svm,
        Instruction {
            program_id,
            accounts: vec![
                AccountMeta::new(pool, false),
                AccountMeta::new(vault, false),
                AccountMeta::new_readonly(mint, false),
                AccountMeta::new(alice.pubkey(), true),
                AccountMeta::new_readonly(token_program, false),
                AccountMeta::new_readonly(system, false),
                AccountMeta::new_readonly(rent, false),
            ],
            data: disc("initialize").to_vec(),
        },
        &alice,
    )
    .expect("initialize");

    // 1) deposit: Alice shields 150
    transact(
        &mut svm,
        program_id,
        mint,
        pool,
        vault,
        &alice,
        alice_token,
        bob_token,
        "dep",
    )
    .expect("deposit");
    assert_eq!(
        token_amount(&svm.get_account(&vault).unwrap()),
        150,
        "vault funded by deposit"
    );
    assert_eq!(
        token_amount(&svm.get_account(&alice_token).unwrap()),
        0,
        "alice drained"
    );

    // 2) transfer: Alice privately pays Bob 100 (50 change) — no tokens move
    transact(
        &mut svm,
        program_id,
        mint,
        pool,
        vault,
        &alice,
        alice_token,
        bob_token,
        "xfer",
    )
    .expect("transfer");
    assert_eq!(
        token_amount(&svm.get_account(&vault).unwrap()),
        150,
        "vault unchanged by shielded transfer"
    );

    // 3) withdraw: Bob unshields 100 to bob_token
    transact(
        &mut svm,
        program_id,
        mint,
        pool,
        vault,
        &alice,
        alice_token,
        bob_token,
        "wd",
    )
    .expect("withdraw");
    assert_eq!(
        token_amount(&svm.get_account(&bob_token).unwrap()),
        100,
        "bob received the withdrawal"
    );
    assert_eq!(
        token_amount(&svm.get_account(&vault).unwrap()),
        50,
        "50 remains shielded (Alice's change)"
    );

    // tree advanced by 6 leaves (2 per transact)
    let pool_acct = svm.get_account(&pool).unwrap();
    assert_eq!(
        u32::from_le_bytes(pool_acct.data[40..44].try_into().unwrap()),
        6
    );
}
