//! Shielded transfer (04) e2e in LiteSVM — the full flow:
//!   deposit (Alice shields 150) -> private transfer (Alice pays Bob 100, 50 change)
//!   -> withdraw (Bob unshields 100).
//!
//! Pre-creates an SPL mint + token accounts via `set_account` (no spl-token
//! instruction crate), then drives three real `transact` proofs generated by
//! circuits/transact/chain/. Each proof carries its own anchor root, nullifiers,
//! output commitments and new root; the program verifies, moves SPL for the
//! public value slots, burns nullifiers, and advances the tree.
use std::path::PathBuf;
use std::str::FromStr;

use litesvm::LiteSVM;
use litesvm::types::TransactionResult;
use sha2::{Digest, Sha256};
use solana_account::Account;
use solana_address::Address;
use solana_instruction::{AccountMeta, Instruction};
use solana_keypair::Keypair;
use solana_message::Message;
use solana_signer::Signer;
use solana_transaction::Transaction;

const PROGRAM_ID: &str = "CUCcJJBRbK6tK4nPP2zgmvdYbKWSCGGVdRegtJ2GPJtF";
const TOKEN_PROGRAM: &str = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const RENT_SYSVAR: &str = "SysvarRent111111111111111111111111111111111";
const SYSTEM: &str = "11111111111111111111111111111111";
const MINT_PUBKEY: [u8; 32] = [
    123, 236, 127, 84, 75, 150, 142, 114, 96, 47, 36, 185, 180, 0, 184, 185, 219, 76, 85, 214, 104,
    64, 213, 210, 101, 226, 248, 208, 110, 243, 181, 54,
];
const CHAIN: &str = "04-shielded-transfer/circuits/transact/chain";

fn disc(name: &str) -> [u8; 8] {
    Sha256::digest(format!("global:{name}").as_bytes())[..8].try_into().unwrap()
}
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}
fn read(rel: &str) -> Vec<u8> {
    let p = repo_root().join(rel);
    std::fs::read(&p).unwrap_or_else(|e| panic!("missing {}: {e}", p.display()))
}
fn chunk32(b: &[u8], i: usize) -> [u8; 32] {
    b[i * 32..i * 32 + 32].try_into().unwrap()
}
fn u64_at(b: &[u8], i: usize) -> u64 {
    u64::from_le_bytes(b[i * 32..i * 32 + 8].try_into().unwrap())
}
fn borsh_bytes(v: &[u8]) -> Vec<u8> {
    let mut out = (v.len() as u32).to_le_bytes().to_vec();
    out.extend_from_slice(v);
    out
}
fn tok(lamports: u64, data: Vec<u8>) -> Account {
    Account { lamports, data, owner: Address::from_str(TOKEN_PROGRAM).unwrap(), executable: false, rent_epoch: 0 }
}
fn mint_data(auth: &[u8; 32]) -> Vec<u8> {
    let mut d = vec![1, 0, 0, 0];
    d.extend_from_slice(auth);
    d.extend_from_slice(&0u64.to_le_bytes());
    d.push(0);
    d.push(1);
    d.extend_from_slice(&[0u8; 36]);
    d
}
fn token_data(mint: &[u8; 32], owner: &[u8; 32], amount: u64) -> Vec<u8> {
    let mut d = Vec::with_capacity(165);
    d.extend_from_slice(mint);
    d.extend_from_slice(owner);
    d.extend_from_slice(&amount.to_le_bytes());
    d.extend_from_slice(&[0u8; 36]);
    d.push(1);
    d.extend_from_slice(&[0u8; 12]);
    d.extend_from_slice(&0u64.to_le_bytes());
    d.extend_from_slice(&[0u8; 36]);
    d
}
fn token_amount(a: &Account) -> u64 {
    u64::from_le_bytes(a.data[64..72].try_into().unwrap())
}
fn send(svm: &mut LiteSVM, ix: Instruction, signer: &Keypair) -> TransactionResult {
    let msg = Message::new(&[ix], Some(&signer.pubkey()));
    svm.send_transaction(Transaction::new(&[signer], msg, svm.latest_blockhash()))
}

#[allow(clippy::too_many_arguments)]
fn transact(
    svm: &mut LiteSVM,
    program_id: Address,
    mint: Address,
    pool: Address,
    vault: Address,
    user: &Keypair,
    user_token: Address,
    recipient_token: Address,
    name: &str,
) -> TransactionResult {
    let proof = read(&format!("{CHAIN}/{name}_proof.bin"));
    let pi = read(&format!("{CHAIN}/{name}_pi.bin"));
    let root = chunk32(&pi, 0);
    let nf0 = chunk32(&pi, 2);
    let nf1 = chunk32(&pi, 3);
    let cm0 = chunk32(&pi, 4);
    let cm1 = chunk32(&pi, 5);
    let new_root = chunk32(&pi, 7);
    let (vpub_in, vpub_out, fee) = (u64_at(&pi, 9), u64_at(&pi, 10), u64_at(&pi, 11));

    let (nullifier0, _) =
        Address::find_program_address(&[b"nullifier", mint.as_ref(), &nf0], &program_id);
    let (nullifier1, _) =
        Address::find_program_address(&[b"nullifier", mint.as_ref(), &nf1], &program_id);

    let token_program = Address::from_str(TOKEN_PROGRAM).unwrap();
    let system = Address::from_str(SYSTEM).unwrap();

    let mut data = disc("transact").to_vec();
    data.extend_from_slice(&borsh_bytes(&proof));
    data.extend_from_slice(&root);
    data.extend_from_slice(&nf0);
    data.extend_from_slice(&nf1);
    data.extend_from_slice(&cm0);
    data.extend_from_slice(&cm1);
    data.extend_from_slice(&new_root);
    data.extend_from_slice(&vpub_in.to_le_bytes());
    data.extend_from_slice(&vpub_out.to_le_bytes());
    data.extend_from_slice(&fee.to_le_bytes());
    data.extend_from_slice(&borsh_bytes(format!("{name}-memo0").as_bytes()));
    data.extend_from_slice(&borsh_bytes(format!("{name}-memo1").as_bytes()));

    let ix = Instruction {
        program_id,
        accounts: vec![
            AccountMeta::new(pool, false),
            AccountMeta::new(vault, false),
            AccountMeta::new(nullifier0, false),
            AccountMeta::new(nullifier1, false),
            AccountMeta::new(user.pubkey(), true),
            AccountMeta::new(user_token, false),
            AccountMeta::new(recipient_token, false),
            AccountMeta::new_readonly(token_program, false),
            AccountMeta::new_readonly(system, false),
        ],
        data,
    };
    send(svm, ix, user)
}

#[test]
fn shielded_transfer_flow() {
    let program_id = Address::from_str(PROGRAM_ID).unwrap();
    let token_program = Address::from_str(TOKEN_PROGRAM).unwrap();
    let system = Address::from_str(SYSTEM).unwrap();
    let rent = Address::from_str(RENT_SYSVAR).unwrap();
    let mint = Address::new_from_array(MINT_PUBKEY);

    let mut svm = LiteSVM::new();
    svm.add_program(program_id, &read("04-shielded-transfer/program/target/deploy/shielded_transfer.so"))
        .unwrap();

    let alice = Keypair::new();
    svm.airdrop(&alice.pubkey(), 5_000_000_000).unwrap();
    svm.set_account(mint, tok(10_000_000, mint_data(&alice.pubkey().to_bytes()))).unwrap();
    let alice_token = Keypair::new().pubkey();
    svm.set_account(alice_token, tok(10_000_000, token_data(&MINT_PUBKEY, &alice.pubkey().to_bytes(), 150)))
        .unwrap();
    let bob_token = Keypair::new().pubkey();
    svm.set_account(bob_token, tok(10_000_000, token_data(&MINT_PUBKEY, &alice.pubkey().to_bytes(), 0)))
        .unwrap();

    let (pool, _) = Address::find_program_address(&[b"pool", mint.as_ref()], &program_id);
    let (vault, _) = Address::find_program_address(&[b"vault", mint.as_ref()], &program_id);

    // initialize
    send(
        &mut svm,
        Instruction {
            program_id,
            accounts: vec![
                AccountMeta::new(pool, false),
                AccountMeta::new(vault, false),
                AccountMeta::new_readonly(mint, false),
                AccountMeta::new(alice.pubkey(), true),
                AccountMeta::new_readonly(token_program, false),
                AccountMeta::new_readonly(system, false),
                AccountMeta::new_readonly(rent, false),
            ],
            data: disc("initialize").to_vec(),
        },
        &alice,
    )
    .expect("initialize");

    // 1) deposit: Alice shields 150
    transact(&mut svm, program_id, mint, pool, vault, &alice, alice_token, bob_token, "dep")
        .expect("deposit");
    assert_eq!(token_amount(&svm.get_account(&vault).unwrap()), 150, "vault funded by deposit");
    assert_eq!(token_amount(&svm.get_account(&alice_token).unwrap()), 0, "alice drained");

    // 2) transfer: Alice privately pays Bob 100 (50 change) — no tokens move
    transact(&mut svm, program_id, mint, pool, vault, &alice, alice_token, bob_token, "xfer")
        .expect("transfer");
    assert_eq!(token_amount(&svm.get_account(&vault).unwrap()), 150, "vault unchanged by shielded transfer");

    // 3) withdraw: Bob unshields 100 to bob_token
    transact(&mut svm, program_id, mint, pool, vault, &alice, alice_token, bob_token, "wd")
        .expect("withdraw");
    assert_eq!(token_amount(&svm.get_account(&bob_token).unwrap()), 100, "bob received the withdrawal");
    assert_eq!(token_amount(&svm.get_account(&vault).unwrap()), 50, "50 remains shielded (Alice's change)");

    // tree advanced by 6 leaves (2 per transact)
    let pool_acct = svm.get_account(&pool).unwrap();
    assert_eq!(u32::from_le_bytes(pool_acct.data[40..44].try_into().unwrap()), 6);
}
